name: Deploy Resource Packs

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout private repo
        uses: actions/checkout@v3

      - name: Zip legacy and new packs
        run: |
          mkdir -p out
          zip -r out/legacy-pack.zip pack/legacy
          zip -r out/new-pack.zip pack/new

      - name: Generate SHA-1 hashes
        run: |
          sha1sum out/legacy-pack.zip | awk '{print $1}' > out/legacy-pack.sha1
          sha1sum out/new-pack.zip | awk '{print $1}' > out/new-pack.sha1

      - name: Checkout public repo
        uses: actions/checkout@v3
        with:
          repository: Nexus-MC/LevelsRM-Packs
          token: ${{ secrets.PUBLIC_REPO_PAT }}
          path: public

      - name: Copy artifacts to public repo
        run: |
          mkdir -p public/legacy public/new
          cp out/legacy-pack.zip public/legacy/
          cp out/legacy-pack.sha1 public/legacy/
          cp out/new-pack.zip public/new/
          cp out/new-pack.sha1 public/new/

      - name: Commit and push
        run: |
          cd public
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add .
          git commit -m "Update resource packs"
          git push
